version: '2'

services:
   db:
     image: mysql:5.7
     container_name: milio_mysql
     volumes:
       - ./db_data:/var/lib/mysql

       # This line is only used for the initial start up (the very first time
       # docker-compose is run or if there is no data in the 'db_data' folder
       - ./initial_sql/neatline_milio.sql:/docker-entrypoint-initdb.d/milio_initial.sql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
       MYSQL_USER: ${MYSQL_USER}
       MYSQL_PASSWORD: ${MYSQL_PASSWORD}
     networks:
       - internal
     labels:
       - "traefik.enable=false"

   milio_omeka:
     build:
       context: .
     depends_on:
       - db
     image: milio:0.4
     container_name: milio_omeka
     #hostname: cnhi-milio.nursing.virginia.edu
     volumes:
       - ./omeka:/var/www/html/
     #ports:
       #- ${PORTS}
     restart: always
     environment:
       OMEKA_DB_HOST: ${OMEKA_DB_HOST}
       OMEKA_DB_USER: ${MYSQL_USER}
       OMEKA_DB_PASSWORD: ${MYSQL_PASSWORD}
       OMEKA_TABLE_PREFIX: ${OMEKA_TABLE_PREFIX}
     networks:
       - traefik-proxy
       - default
       - internal
     expose:
       - "80"
     labels:
       - "traefik.docker.network=traefik-proxy"
       - "traefik.enable=true"
       - "traefik.port=80"
       - "traefik.backend=milio_omeka"
       - "traefik.frontend.rule=Host:cnhi-milio.nursing.virginia.edu"
networks:
  traefik-proxy:
    external: true
  internal:
    external: false
