#!/bin/bash

TAG=$(git tag -l | tail -1)

echo "Upgrading to $TAG..."
echo

git stash save $TAG
git fetch origin
git checkout $TAG
git submodule update
git stash pop $TAG

echo
echo "Done"
echo "Please log in to http://cnhi-milio.nursing.virginia.edu/admin/."
echo "You may need to upgrade the database or some plugins."
